on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: Install the project
        working-directory: ./python
        run: uv sync --dev
      - name: Run tests
        working-directory: ./python
        run: uv run pytest
      - name: Build
        working-directory: ./python
        run: uv build
      - name: Publish
        working-directory: ./python
        run: uv publish