on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: Install the project
        working-directory: ./python
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        id: test_result
        run: |
          if $(uv run pytest); then
            echo "::set-output name=result::success"
          else
            echo "::set-output name=result::failure"
          fi
      - name: Send fail message to PR
        if: steps.test_result.outputs.result == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Test Results
            PYTHON: Some tests failed! ‚ùå Please check the logs for more details.
      - name: Send success message to PR
        if: steps.test_result.outputs.result == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Test Results
            PYTHON: All tests have passed successfully! üéâ