on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Go to python directory
        run: |
          cd python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install current library
        run: |
          pip install .
      - name: Run tests
        id: test_result
        run: |
          if pytest; then
            echo "::set-output name=result::success"
          else
            echo "::set-output name=result::failure"
          fi
      - name: Send fail message to PR
        if: steps.test_result.outputs.result == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Test Results
            PYTHON: Some tests failed! ‚ùå Please check the logs for more details.
      - name: Send success message to PR
        if: steps.test_result.outputs.result == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## Test Results
            PYTHON: All tests have passed successfully! üéâ